{
 "title": "Application Resource Health",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": "ml-api,backend-api" }
  ]
 },
 "panels": [
  { "title": "K8s Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(container) (node_namespace_pod_container:container_memory_working_set_bytes{container=\"$application\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg by (namespace, container) (\n  kube_pod_container_resource_requests{\n    namespace=\"$application\",\n    container=\"$application\",\n    resource=\"memory\"\n  }\n)",
     "legendFormat": "Requests"
    },
    {
     "expr": "avg by (namespace, container) (\n  kube_pod_container_resource_limits{\n    namespace=\"$application\",\n    container=\"$application\",\n    resource=\"memory\"\n  }\n)",
     "legendFormat": "Limits"
    },
    {
     "expr": "avg by(container) (process_resident_memory_bytes{namespace=\"$application\"})",
     "legendFormat": "RSS Memory"
    }
   ]
  },
  {
   "title": "Pod CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "avg by(container) (\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{\n    namespace=\"$application\",\n    container=\"$application\"\n  }\n)",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg by (namespace, container) (\n  kube_pod_container_resource_requests{\n    namespace=\"$application\",\n    container=\"$application\",\n    resource=\"cpu\"\n  }\n)\n",
     "legendFormat": "Requests"
    },
    {
     "expr": "avg by (namespace, container) (\n  kube_pod_container_resource_limits{\n    namespace=\"$application\",\n    container=\"$application\",\n    resource=\"cpu\"\n  }\n)\n",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "OOM Killed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      container_oom_events_total{\n        namespace=\"$application\",\n        container=\"$application\"\n      }[$__range]\n    )\n  )\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      kube_pod_container_status_restarts_total{\n        namespace=\"$application\",\n        container=\"$application\"\n      }[$__range]\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$application\",condition=\"true\"})"
    }
   ]
  },
  {
   "title": "Unready Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"$application\"}) - sum(kube_pod_status_ready{namespace=\"$application\",condition=\"true\"})"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{namespace=~\"${application}\"}\n| pattern `<log_type>: <_> <source_ip>:<source_port> - \"<method> <endpoint> HTTP/<http_version>\" <status_code> <status_text>`\n| line_format `{{ printf \"%-5s | %-15s | %-6s | %-12s | %3s | %s\" .log_type .source_ip .method .endpoint .status_code .status_text }}`\n"
    }
   ]
  }
 ]
}