{
 "title": "ML API Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "ML API Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request rate by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(ml_api_requests_total[$__rate_interval]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status,endpoint ) (rate(ml_api_requests_total[$__rate_interval]))",
     "legendFormat": "HTTP {{status}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Prediction rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ml_api_predictions_total[$__rate_interval]))",
     "legendFormat": "predictions/s"
    }
   ]
  },
  {
   "title": "Prediction Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (\n  rate(ml_api_request_duration_seconds_sum[$__rate_interval])\n)\n/\nsum by (endpoint) (\n  rate(ml_api_request_duration_seconds_count[$__rate_interval])\n)\n",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "P95 request latency by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, endpoint) (rate(ml_api_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "5xx error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(ml_api_requests_total{status=~\"5..\"}[$__rate_interval])) / clamp_min(sum(rate(ml_api_requests_total[$__rate_interval])), 1e-9)",
     "legendFormat": "5xx error rate"
    }
   ]
  }
 ]
}