{
 "title": "PostgreSQL Overview",
 "tags": [
  "devops-case-study",
  "postgresql",
  "database"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "PostgreSQL exporter status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "min(pg_up)" }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname)(pg_stat_database_numbackends)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transaction commit rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_database_xact_commit[$__rate_interval]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Transaction rollback rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_database_xact_rollback[$__rate_interval]))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Buffer cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(pg_stat_database_blks_hit[$__rate_interval])) / clamp_min(sum(rate(pg_stat_database_blks_hit[$__rate_interval])) + sum(rate(pg_stat_database_blks_read[$__rate_interval])), 1)",
     "legendFormat": "cache hit ratio"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg_database_size_bytes)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (\n  increase(\n    pg_stat_database_deadlocks[$__rate_interval]\n  )\n)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Temporary data written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_database_temp_bytes[$__rate_interval]))",
     "legendFormat": "{{datname}}"
    }
   ]
  }
 ]
}