apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-api
  namespace: backend-api
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: backend-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      honorLabels: true
